name: Windows C++ Tests

on: [push]

jobs:
  build:
    runs-on: windows-latest  # This will run on a Windows runner

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: threeal/cmake-action@v2.1.0
      with:
        generator: Ninja
        cxx-compiler: C:/mingw64/bin/g++.exe 

    - name: Run the executable
      run: |
        cd build
        ./licprocman.exe