name: Windows C++ Tests

on: [push]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies (Make + MinGW)
      shell: pwsh
      run: |
        choco install make mingw -y
        echo "C:\ProgramData\chocolatey\lib\make\tools\install\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

    - name: Build with Make
      shell: pwsh
      run: |
        cd build
        make

    - name: Run tests
      shell: pwsh
      run: |
        cd build
        .\libprocman.exe