name: Windows C++ Tests

on: [push]

jobs:
  build:
    runs-on: windows-latest  # This will run on a Windows runner

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: actions/setup-cmake@v2
      with:
        cmake-version: '3.21.2'

    - name: Set up MinGW (make)
      uses: msys2/setup-msys2-action@v2
      with:
        update: true

    - name: Install required dependencies
      run: |
        pacman -S --noconfirm mingw-w64-x86_64-toolchain make

    - name: Configure and build with CMake
      run:
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_C_COMPILER="C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/gcc.exe" -DCMAKE_CXX_COMPILER="C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/g++.exe"
        cmake --build .

    - name: Run the executable
      run: ./licprocman.exe